version: '3.4'

services:
  learningdiary.api:
    image: ${DOCKER_REGISTRY-}learningdiaryapi:0.1.0
    build:
      context: .
      dockerfile: src/LearningDiary.API/Dockerfile

  learningdiary.webui:
    image: ${DOCKER_REGISTRY-}learningdiarywebui:0.1.0
    build:
      context: .
      dockerfile: src/LearningDiary.WebUI/Dockerfile