version: '3.4'

services:
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  learningdiary.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://0.0.0.0:80/
      - "MongoDbSettings:ConnectionString=mongodb://mongodb:27017"
      - "MongoDbSettings:Database=learningdiary"
    ports:
      - "3000:80"
    depends_on:
      - mongodb

  learningdiary.webui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "Clients:SavePoint=http://learningdiary.api"
    ports:
      - "3001:80"